/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// RepackPolicyLister helps list RepackPolicies.
// All objects returned here must be treated as read-only.
type RepackPolicyLister interface {
	// List lists all RepackPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*repackv1alpha1.RepackPolicy, err error)
	// Get retrieves the RepackPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*repackv1alpha1.RepackPolicy, error)
	RepackPolicyListerExpansion
}

// repackPolicyLister implements the RepackPolicyLister interface.
type repackPolicyLister struct {
	listers.ResourceIndexer[*repackv1alpha1.RepackPolicy]
}

// NewRepackPolicyLister returns a new RepackPolicyLister.
func NewRepackPolicyLister(indexer cache.Indexer) RepackPolicyLister {
	return &repackPolicyLister{listers.New[*repackv1alpha1.RepackPolicy](indexer, repackv1alpha1.Resource("repackpolicy"))}
}
