/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	repackv1alpha1 "volcano.sh/apis/pkg/apis/repack/v1alpha1"
)

// NetworkTopologyApplyConfiguration represents a declarative configuration of the NetworkTopology type for use
// with apply.
//
// NetworkTopology specifies the HyperNode-tier fragmentation optimization target
// of one RepackRun: free at least RequiredNodeBlocks blocks of NodeBlockSize
// nodes within exactly one HyperNode tier.
//
// The tier identifier is mutually exclusive by construction: configure exactly
// one of HyperNodeTier (numeric, matching HyperNode.Spec.Tier) or
// HyperNodeTierName (matching HyperNode.Spec.TierName). The exclusivity is
// enforced at the apiserver with a CEL XValidation on this struct (there is no
// repo precedent for struct-level XValidation; verify via make manifests + e2e).
type NetworkTopologyApplyConfiguration struct {
	// HyperNodeTier is the target HyperNode tier (numeric), matching
	// HyperNode.Spec.Tier. Mutually exclusive with HyperNodeTierName; exactly one
	// must be configured (enforced by CEL).
	HyperNodeTier *int `json:"hyperNodeTier,omitempty"`
	// HyperNodeTierName is the target HyperNode tier name, matching
	// HyperNode.Spec.TierName. Mutually exclusive with HyperNodeTier; exactly one
	// must be configured (enforced by CEL).
	HyperNodeTierName *string `json:"hyperNodeTierName,omitempty"`
	// NodeBlockSize is the number of nodes in one block. A block must lie entirely
	// inside a single HyperNode of the target tier: nodes from different HyperNodes
	// cannot be combined into one block. It is a pointer so that an explicit 0 is
	// distinguishable from "omitted": 0 is rejected by the minimum:1 rule (a block
	// must hold at least one node), while omitting the field applies the default 1
	// (each node is a block).
	NodeBlockSize *int `json:"nodeBlockSize,omitempty"`
	// RequiredNodeBlocks is the minimum number of blocks the defragmentation must
	// free. The target is met only when at least RequiredNodeBlocks blocks are
	// freed; if it cannot be met, the plan is infeasible and no defragmentation is
	// performed. 0 (default) relaxes the gate entirely: the block semantics degrade
	// to pure soft guidance. Must be non-negative.
	RequiredNodeBlocks *int `json:"requiredNodeBlocks,omitempty"`
	// Mode expresses how blocks should be distributed across HyperNodes: binpack
	// concentrates blocks onto as few HyperNodes as possible; spread disperses
	// them. Omitted = no distribution preference.
	Mode *repackv1alpha1.RepackBlockMode `json:"mode,omitempty"`
}

// NetworkTopologyApplyConfiguration constructs a declarative configuration of the NetworkTopology type for use with
// apply.
func NetworkTopology() *NetworkTopologyApplyConfiguration {
	return &NetworkTopologyApplyConfiguration{}
}

// WithHyperNodeTier sets the HyperNodeTier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HyperNodeTier field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithHyperNodeTier(value int) *NetworkTopologyApplyConfiguration {
	b.HyperNodeTier = &value
	return b
}

// WithHyperNodeTierName sets the HyperNodeTierName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HyperNodeTierName field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithHyperNodeTierName(value string) *NetworkTopologyApplyConfiguration {
	b.HyperNodeTierName = &value
	return b
}

// WithNodeBlockSize sets the NodeBlockSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeBlockSize field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithNodeBlockSize(value int) *NetworkTopologyApplyConfiguration {
	b.NodeBlockSize = &value
	return b
}

// WithRequiredNodeBlocks sets the RequiredNodeBlocks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredNodeBlocks field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithRequiredNodeBlocks(value int) *NetworkTopologyApplyConfiguration {
	b.RequiredNodeBlocks = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *NetworkTopologyApplyConfiguration) WithMode(value repackv1alpha1.RepackBlockMode) *NetworkTopologyApplyConfiguration {
	b.Mode = &value
	return b
}
