/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RepackRunTemplateSpecApplyConfiguration represents a declarative configuration of the RepackRunTemplateSpec type for use
// with apply.
//
// RepackRunTemplateSpec wraps a RepackRun spec along with metadata labels/annotations.
type RepackRunTemplateSpecApplyConfiguration struct {
	// ObjectMeta carries labels and annotations to propagate to generated Runs.
	ObjectMeta *v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// Spec is the RepackRunSpec to deep-copy into each generated Run.
	Spec *RepackRunSpecApplyConfiguration `json:"spec,omitempty"`
}

// RepackRunTemplateSpecApplyConfiguration constructs a declarative configuration of the RepackRunTemplateSpec type for use with
// apply.
func RepackRunTemplateSpec() *RepackRunTemplateSpecApplyConfiguration {
	return &RepackRunTemplateSpecApplyConfiguration{}
}

// WithObjectMeta sets the ObjectMeta field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectMeta field is set to the value of the last call.
func (b *RepackRunTemplateSpecApplyConfiguration) WithObjectMeta(value *v1.ObjectMetaApplyConfiguration) *RepackRunTemplateSpecApplyConfiguration {
	b.ObjectMeta = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *RepackRunTemplateSpecApplyConfiguration) WithSpec(value *RepackRunSpecApplyConfiguration) *RepackRunTemplateSpecApplyConfiguration {
	b.Spec = value
	return b
}
