/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RepackPolicyStatusApplyConfiguration represents a declarative configuration of the RepackPolicyStatus type for use
// with apply.
//
// RepackPolicyStatus communicates the observed state of a RepackPolicy.
// Inspired by CronJobStatus but uses conditions instead of Active list solely,
// and adds lastEvaluationTime for reactive-trigger tracking.
type RepackPolicyStatusApplyConfiguration struct {
	// InProgress lists generated Runs that have not yet reached a terminal phase.
	// Terminal (Succeeded/Failed) runs are removed.
	InProgress []v1.ObjectReference `json:"inProgress,omitempty"`
	// LastTriggerTime is the most recent time a Run was generated (any trigger source).
	LastTriggerTime *metav1.Time `json:"lastTriggerTime,omitempty"`
	// LastSuccessfulTime is the completion time of the most recent successful Run.
	LastSuccessfulTime *metav1.Time `json:"lastSuccessfulTime,omitempty"`
	// LastEvaluationTime is the most recent reactive-trigger evaluation time.
	LastEvaluationTime *metav1.Time `json:"lastEvaluationTime,omitempty"`
	// Conditions expresses the policy's health. The only condition type is
	// "Healthy": True=ReconcileSucceeded, False=ReconcileFailed.
	Conditions []applyconfigurationsmetav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// RepackPolicyStatusApplyConfiguration constructs a declarative configuration of the RepackPolicyStatus type for use with
// apply.
func RepackPolicyStatus() *RepackPolicyStatusApplyConfiguration {
	return &RepackPolicyStatusApplyConfiguration{}
}

// WithInProgress adds the given value to the InProgress field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InProgress field.
func (b *RepackPolicyStatusApplyConfiguration) WithInProgress(values ...v1.ObjectReference) *RepackPolicyStatusApplyConfiguration {
	for i := range values {
		b.InProgress = append(b.InProgress, values[i])
	}
	return b
}

// WithLastTriggerTime sets the LastTriggerTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTriggerTime field is set to the value of the last call.
func (b *RepackPolicyStatusApplyConfiguration) WithLastTriggerTime(value metav1.Time) *RepackPolicyStatusApplyConfiguration {
	b.LastTriggerTime = &value
	return b
}

// WithLastSuccessfulTime sets the LastSuccessfulTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulTime field is set to the value of the last call.
func (b *RepackPolicyStatusApplyConfiguration) WithLastSuccessfulTime(value metav1.Time) *RepackPolicyStatusApplyConfiguration {
	b.LastSuccessfulTime = &value
	return b
}

// WithLastEvaluationTime sets the LastEvaluationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastEvaluationTime field is set to the value of the last call.
func (b *RepackPolicyStatusApplyConfiguration) WithLastEvaluationTime(value metav1.Time) *RepackPolicyStatusApplyConfiguration {
	b.LastEvaluationTime = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RepackPolicyStatusApplyConfiguration) WithConditions(values ...*applyconfigurationsmetav1.ConditionApplyConfiguration) *RepackPolicyStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
