/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackRunTriggerApplyConfiguration represents a declarative configuration of the RepackRunTrigger type for use
// with apply.
//
// RepackRunTrigger specifies the trigger sources. At least one must be set.
type RepackRunTriggerApplyConfiguration struct {
	// CronSchedule is a standard 5-field cron expression (e.g. "0 */6 * * *").
	// Omitted or empty string means cron triggering is disabled.
	CronSchedule *string `json:"cronSchedule,omitempty"`
	// OnFragAbovePercent triggers when cluster fragmentation exceeds this
	// percentage (0–100). 0 or nil means reactive triggering is disabled.
	OnFragAbovePercent *int32 `json:"onFragAbovePercent,omitempty"`
}

// RepackRunTriggerApplyConfiguration constructs a declarative configuration of the RepackRunTrigger type for use with
// apply.
func RepackRunTrigger() *RepackRunTriggerApplyConfiguration {
	return &RepackRunTriggerApplyConfiguration{}
}

// WithCronSchedule sets the CronSchedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CronSchedule field is set to the value of the last call.
func (b *RepackRunTriggerApplyConfiguration) WithCronSchedule(value string) *RepackRunTriggerApplyConfiguration {
	b.CronSchedule = &value
	return b
}

// WithOnFragAbovePercent sets the OnFragAbovePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnFragAbovePercent field is set to the value of the last call.
func (b *RepackRunTriggerApplyConfiguration) WithOnFragAbovePercent(value int32) *RepackRunTriggerApplyConfiguration {
	b.OnFragAbovePercent = &value
	return b
}
