/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RepackPolicySpecApplyConfiguration represents a declarative configuration of the RepackPolicySpec type for use
// with apply.
//
// RepackPolicySpec defines the desired state of a RepackPolicy.
type RepackPolicySpecApplyConfiguration struct {
	// Trigger specifies when to generate a RepackRun (at least one source required).
	Trigger *RepackRunTriggerApplyConfiguration `json:"trigger,omitempty"`
	// RunTemplate is the template from which RepackRuns are created.
	RunTemplate *RepackRunTemplateSpecApplyConfiguration `json:"runTemplate,omitempty"`
	// Suspend suspends trigger evaluation (existing Runs unaffected). Defaults to false.
	Suspend *bool `json:"suspend,omitempty"`
	// SuccessfulRunsHistoryLimit is how many successful Runs to keep (0 = none). Defaults to 3.
	SuccessfulRunsHistoryLimit *int32 `json:"successfulRunsHistoryLimit,omitempty"`
	// FailedRunsHistoryLimit is how many failed Runs to keep (0 = none). Defaults to 3.
	FailedRunsHistoryLimit *int32 `json:"failedRunsHistoryLimit,omitempty"`
}

// RepackPolicySpecApplyConfiguration constructs a declarative configuration of the RepackPolicySpec type for use with
// apply.
func RepackPolicySpec() *RepackPolicySpecApplyConfiguration {
	return &RepackPolicySpecApplyConfiguration{}
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *RepackPolicySpecApplyConfiguration) WithTrigger(value *RepackRunTriggerApplyConfiguration) *RepackPolicySpecApplyConfiguration {
	b.Trigger = value
	return b
}

// WithRunTemplate sets the RunTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunTemplate field is set to the value of the last call.
func (b *RepackPolicySpecApplyConfiguration) WithRunTemplate(value *RepackRunTemplateSpecApplyConfiguration) *RepackPolicySpecApplyConfiguration {
	b.RunTemplate = value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *RepackPolicySpecApplyConfiguration) WithSuspend(value bool) *RepackPolicySpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithSuccessfulRunsHistoryLimit sets the SuccessfulRunsHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessfulRunsHistoryLimit field is set to the value of the last call.
func (b *RepackPolicySpecApplyConfiguration) WithSuccessfulRunsHistoryLimit(value int32) *RepackPolicySpecApplyConfiguration {
	b.SuccessfulRunsHistoryLimit = &value
	return b
}

// WithFailedRunsHistoryLimit sets the FailedRunsHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedRunsHistoryLimit field is set to the value of the last call.
func (b *RepackPolicySpecApplyConfiguration) WithFailedRunsHistoryLimit(value int32) *RepackPolicySpecApplyConfiguration {
	b.FailedRunsHistoryLimit = &value
	return b
}
